version: '3.8'

services:

  forum-main-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: 'music-forum'
      POSTGRES_USER: 'music-forum'
      POSTGRES_PASSWORD: 'music-forum'
    volumes:
      - ./forum-main-db:/var/lib/postgresql/data
    ports:
      - 5432:5432 # default port

  forum-fallback-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: 'music-forum'
      POSTGRES_USER: 'music-forum'
      POSTGRES_PASSWORD: 'music-forum'
    volumes:
      - ./forum-fallback-db:/var/lib/postgresql/data
    ports:
      - 5433:5432 # different port