version: '3.8'

services:

  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: 'music-forum'
      POSTGRES_USER: 'music-forum'
      POSTGRES_PASSWORD: 'music-forum'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432