spring:

  application:
    name: report-ms

  profiles:
    default: default

  config:
    import: "optional:configserver:http://localhost:7777"

server:
  servlet:
    context-path: /forum-crud
  port: 0

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
