spring:
  datasource:
    username: music-forum
    password: music-forum
    url: jdbc:postgresql://localhost:5433/music-forum
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: "update"