spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      username: music-forum
      password: music-forum
      database: reports
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
    